<div style="display:block" direction=rtl align=right><br><br>
    <div  style="width:100%;margin:100;display:block"  display=block align=center>
        <img width=130 align=right src="https://i.ibb.co/yXKQmtZ/logo1.png" style="margin:0;" />
        <img width=170 align=left  src="https://i.ibb.co/wLjqFkw/logo2.png" style="margin:0;" />
        <span><br><font size=5>University of Tehran , school of ECE</font></span>
        <span><br><font size=3>Deep Learning</font></span>
        <span><br><font size=3>Spring 2023</font></span>
    </div><br><br><br>
    <div style="display:block" align=left display=block> 
        <font size=3>Pytorch tutorial - Introduction</font><br>
        <hr />
        <font size=3>TA: <a href="mailto:farshads7778@gmail.com">Farshad Sangari</a></font><br>
    </div>
</div>

## Introduction

#### Pytorch

| Feature | Description |
| --- | --- |
| Dynamic computational graph | PyTorch uses a dynamic computational graph that allows for more flexible model building and experimentation. This means that the graph is built on-the-fly during execution, which is particularly useful when building complex, custom models. |
| Easy to use | PyTorch has a simple and intuitive API, which makes it easy to use for researchers and developers. Additionally, it has good documentation and a large community that provides support and resources. |
| GPU acceleration | PyTorch supports GPU acceleration, which allows for faster training of deep learning models on large datasets. |
| TorchScript | PyTorch's TorchScript allows for easy deployment of models in production environments. It enables models to be compiled to a highly optimized form, improving inference speed and efficiency. |
| Active development | PyTorch is under active development and has a strong community that is constantly contributing to its development, adding new features and improving its performance. |


## Installation

In [45]:
#conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia

## Import libraries

In [1]:
import torch
import numpy as np

## Create tensor

### From list

In [ ]:
torch.tensor(lst,requires_grad=True)

In [46]:
lst = [1,2,3,4]
tensor = torch.tensor(lst)
tensor

tensor([1, 2, 3, 4])

### From an array

In [47]:
arr = np.arange(0,10,0.5).reshape((4,5))
arr

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [6]:
tensor = torch.from_numpy(arr)
# torch.tensor(arr)
tensor

tensor([[0.0000, 0.5000, 1.0000, 1.5000, 2.0000],
        [2.5000, 3.0000, 3.5000, 4.0000, 4.5000],
        [5.0000, 5.5000, 6.0000, 6.5000, 7.0000],
        [7.5000, 8.0000, 8.5000, 9.0000, 9.5000]], dtype=torch.float64)

## Convert tensor to numpy

In [48]:
tensor1 = torch.randn(size=(2,3))
tensor1

tensor([[ 0.7465, -0.7677,  0.3285],
        [ 0.9505, -2.0108,  0.8239]])

In [ ]:
tensor1.numpy()

array([[ 0.8154926 ,  0.2954548 ,  0.27072006],
       [-0.43916583, -0.5230534 , -0.5413519 ]], dtype=float32)

## Some special forms

In [3]:
tensor_shape = (3,4)

### Ones tensor

In [5]:
torch.ones(tensor_shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Zeros tensor

In [9]:
torch.zeros(tensor_shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Diagonal tensor

In [50]:
tensor = torch.randint(10,(4,))
tensor

tensor([7, 1, 7, 9])

In [51]:
torch.diag(tensor)

tensor([[7, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 7, 0],
        [0, 0, 0, 9]])

## Random tensors

### Uniformly from the interval [0, 1) tensor

In [10]:
torch.rand(tensor_shape)

tensor([[0.6110, 0.1217, 0.0567, 0.4756],
        [0.6581, 0.0156, 0.2570, 0.3913],
        [0.7994, 0.4307, 0.6324, 0.9574]])

### Uniformly from the interval [low, high) tensor

In [11]:
torch.randint(low=2,high=6,size=tensor_shape)

tensor([[2, 3, 5, 2],
        [4, 3, 5, 2],
        [4, 5, 4, 2]])

### Standard distribution

In [14]:
torch.randn(tensor_shape)

tensor([[ 1.3211,  0.1759, -1.4510,  1.5198],
        [ 0.4456, -0.2399,  0.4471,  1.3005],
        [-2.0173,  0.6138, -1.2153, -0.4869]])

### Normal distribution with mean: `mean` and standard deviation: `std`

In [15]:
torch.normal(mean=0,std=2,size=tensor_shape)

tensor([[ 0.1673, -0.9030,  1.0035,  0.2745],
        [-0.2442,  1.4429, -1.0551, -0.3055],
        [ 4.4262, -1.8558,  2.8828, -2.8617]])

## Same size tensor

In [52]:
tensor1 = torch.randn(size=(2,3))

In [53]:
torch.ones_like(tensor1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.zeros_like(tensor1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch.randint_like(tensor1,1,5)

tensor([[1., 4., 3.],
        [2., 3., 1.]])

## Concatination

In [54]:
tensor1 = torch.randint(0,5,(6,2))
tensor2 = torch.randint(5,10,(6,2))
new_tensor = torch.cat([tensor1,tensor2],dim=1)
print(new_tensor,"\n\n")
print(new_tensor.shape)

tensor([[0, 1, 9, 5],
        [3, 3, 7, 7],
        [4, 2, 9, 9],
        [0, 3, 8, 5],
        [1, 4, 7, 6],
        [4, 3, 5, 9]]) 


torch.Size([6, 4])


## Stacking

In [55]:
new_tensor = torch.stack([tensor1,tensor2],dim=1)
print(new_tensor,"\n\n")
print(new_tensor.shape)

tensor([[[0, 1],
         [9, 5]],

        [[3, 3],
         [7, 7]],

        [[4, 2],
         [9, 9]],

        [[0, 3],
         [8, 5]],

        [[1, 4],
         [7, 6]],

        [[4, 3],
         [5, 9]]]) 


torch.Size([6, 2, 2])


## Multiplication

### Elementwise multiplication

In [56]:
tensor1 = torch.randint(0,5,(6,2))
tensor2 = torch.randint(5,10,(6,2))

#### Method1

In [25]:
tensor1.mul(tensor2)

tensor([[24,  0],
        [ 0,  0],
        [ 0,  5],
        [27, 21],
        [18,  0],
        [14, 16]])

#### Method2

In [26]:
tensor1*tensor2

tensor([[24,  0],
        [ 0,  0],
        [ 0,  5],
        [27, 21],
        [18,  0],
        [14, 16]])

### Matrix multiplication

In [57]:
tensor1 = torch.randint(0,5,(2,6))
tensor2 = torch.randint(5,10,(6,2))

#### Method1

In [28]:
tensor1.matmul(tensor2)

tensor([[ 99, 118],
        [ 87,  91]])

#### Method2

In [29]:
tensor1@tensor2

tensor([[ 99, 118],
        [ 87,  91]])

## Rearrange dimensions

### `.view()` vs `.reshape()`

Here's a table that summarizes the differences between view and reshape in PyTorch:
|          | `view`                              | `reshape`                         |
|----------|-------------------------------------|----------------------------------|
| New Data | No, shares data with original tensor | Yes, may create a copy of data    |
| Speed    | Fast                                | Slower than `view`                |


In general, if you want to modify the shape of a tensor without copying its underlying data, you should use view(). However, if you want to create a new tensor with a different shape, you should use reshape()

#### `.reshape()`

In [58]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
print(tensor)
print(tensor.shape,"\n\n")

new_tensor = tensor.reshape([6])
print(new_tensor)
print(new_tensor.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3]) 


tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])


#### `.view()`

In [61]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
print(tensor)
print(tensor.shape,"\n\n")

new_tensor = tensor.view([-1])
print(new_tensor)
print(new_tensor.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3]) 


tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])


In [64]:
new_tensor[5] = torch.tensor(10)

In [66]:
tensor

tensor([[ 1,  2,  3],
        [ 4,  5, 10]])

### `.transpose()` vs `.permute()`

#### `.transpose()`
* The transpose() function is used to switch the dimensions of a tensor. It takes a tensor as input and returns a new tensor with the dimensions transposed. For example, if the original tensor has shape (a, b, c), the transposed tensor will have shape (c, b, a)

In [71]:
# create a tensor of shape (3, 4, 5)
x = torch.randn(3, 4, 5)

# transpose the tensor to shape (5, 4, 3)
y = x.transpose(0, 2).transpose(0,1)
y.shape

torch.Size([4, 5, 3])

#### `.permute()`
* The permute() function is similar to transpose(), but it allows you to specify the order of the dimensions in the output tensor. It takes a tensor and a list of dimension indices as input and returns a new tensor with the dimensions permuted according to the indices. For example, if the original tensor has shape (a, b, c), and you want the output tensor to have shape (b, c, a), you can call tensor.permute(1, 2, 0).

In [70]:
# create a tensor of shape (3, 4, 5)
x = torch.randn(3, 4, 5)

# permute the tensor to shape (4, 5, 3)
z = x.permute(1, 2, 0)

In [72]:
x = torch.randn(3, 4, 5)

In [75]:
x.numpy().transpose((1,2,0)).shape

(4, 5, 3)

### `.squeeze()` and `.unsqueeze()`

* squeeze() and unsqueeze() are PyTorch tensor manipulation functions that are used to add or remove dimensions from a tensor.

#### `.squeeze()`
* The squeeze() function is used to remove dimensions of size 1 from a tensor. It takes a tensor as input and returns a new tensor with all dimensions of size 1 removed.

In [77]:
# create a tensor of shape (1,1,3)
x = torch.tensor([[[1, 2, 3]]])

# squeeze the tensor to remove the first dimension
y = torch.squeeze(x)

# print the shape of the original and squeezed tensors
print(x.shape)  # torch.Size([1,1, 3])
print(y.shape)  # torch.Size([1,3])

torch.Size([1, 1, 3])
torch.Size([3])


In [78]:
y

tensor([1, 2, 3])

#### `.unsqueeze()`
* The unsqueeze() function is used to add a new dimension to a tensor at a specified position. It takes a tensor and a dimension index as input and returns a new tensor with the specified dimension added.

In [79]:
# create a tensor of shape (3,)
x = torch.tensor([1, 2, 3])

# unsqueeze the tensor to add a new dimension at position 0
y = torch.unsqueeze(x, 0)

# print the shape of the original and unsqueezed tensors
print(x.shape)  # torch.Size([3])
print(y.shape)  # torch.Size([1, 3])

torch.Size([3])
torch.Size([1, 3])


### `.flatten()`

* The flatten() function is used to convert a tensor with multiple dimensions into a 1-dimensional tensor. It takes a tensor as input and returns a new tensor with all dimensions flattened.

In [80]:
# create a tensor of shape (3, 4, 5)
x = torch.randn(3, 4, 5)

# flatten the tensor to shape (60,)
v = x.flatten()
v

tensor([-0.4522,  1.1899,  1.7642, -0.6383, -0.5671,  1.0328,  0.4886, -1.6616,
        -0.8207,  0.2764, -1.0302, -0.1928, -0.6488,  1.1651, -0.2780, -2.2664,
        -1.1547, -0.4329,  0.4301, -0.6520, -0.2780, -1.8682,  0.1130,  1.6779,
        -0.4416, -0.7924, -1.0833,  1.2409,  1.3294, -0.9036,  0.6870,  1.0764,
        -1.8651, -0.2699,  1.0972,  0.5477, -0.4268,  0.8046, -1.2168,  0.3706,
        -2.8509,  1.6846, -0.2054, -0.2326, -0.8687,  0.3140,  0.2960,  2.3124,
        -1.0229,  0.4334, -1.1410,  1.4132, -1.4308, -0.6203,  0.5739,  0.7220,
         1.0646, -0.0639,  0.3601, -0.6900])

## Contigous

`.is_contiguous()`

In [36]:
tensor = torch.randint(20,[2,3])
print("Init tensor: \n",tensor,"\n", "Contigous: ", tensor.is_contiguous(),"\n\n")

transposed_tensor = tensor.transpose(1,0)
print("Here is the transposed tensor: \n",transposed_tensor,"\n", "Contigous: ", transposed_tensor.is_contiguous(),"\n\n")

Init tensor: 
 tensor([[ 6, 14, 17],
        [ 3,  7,  2]]) 
 Contigous:  True 


Here is the transposed tensor: 
 tensor([[ 6,  3],
        [14,  7],
        [17,  2]]) 
 Contigous:  False 




`.contiguous()`

In [37]:
cont_tensor = transposed_tensor.contiguous()
cont_tensor.is_contiguous()

True

## Some methods

#### `.numel()`

In [81]:
tensor = torch.randint(1,10,[3,4,10])
print(f"shape of this tensor is: {tensor.shape}")
print(f"outout of numer method is: {torch.numel(tensor)}")

shape of this tensor is: torch.Size([3, 4, 10])
outout of numer method is: 120


#### `.to()`

In [6]:
tensor = torch.randint(1,10,[3,4])
tensor = tensor.to(torch.float64)
tensor

tensor([[1., 7., 1., 2.],
        [5., 8., 7., 9.],
        [9., 9., 2., 8.]], dtype=torch.float64)